# Generated by Django 6.1 on 2026-09-28 12:31

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(help_text='Patente única del vehículo (ej: ABCD-12).', max_length=10, unique=True, verbose_name='Patente (PPU)')),
                ('modelo', models.CharField(help_text='Ej: Marcopolo Paradiso 1800 DD.', max_length=100, verbose_name='Modelo del Bus')),
                ('marca', models.CharField(default='Scania', max_length=100, verbose_name='Marca del Chasis/Carrocería')),
                ('capacidad_total', models.PositiveIntegerField(help_text='Cantidad máxima física de asientos del bus.', verbose_name='Capacidad Total de Asientos')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el bus está habilitado para ser asignado a servicios.', verbose_name='¿Bus Operativo?')),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Buses',
                'ordering': ['patente'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('PASAJERO', 'Pasajero'), ('ADMIN_FLOTA', 'Administrador de Flota')], default='PASAJERO', help_text='Define si el usuario es un Pasajero (cliente) o un Administrador de Flota.', max_length=20, verbose_name='Rol de Usuario')),
                ('rut', models.CharField(blank=True, help_text='Identificador legal del usuario (ej: 12345678-9).', max_length=15, null=True, verbose_name='RUT / Pasaporte')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de Contacto')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Número de Asiento')),
                ('tipo', models.CharField(choices=[('SEMICAMA', 'Semicama'), ('CAMA', 'Cama')], default='SEMICAMA', max_length=20, verbose_name='Tipo / Confort del Asiento')),
                ('piso', models.PositiveSmallIntegerField(default=1, verbose_name='Piso del Bus (1 o 2)')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='transporte.bus', verbose_name='Bus Asignado')),
            ],
            options={
                'verbose_name': 'Asiento',
                'verbose_name_plural': 'Asientos',
                'ordering': ['bus', 'piso', 'numero'],
                'unique_together': {('bus', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='CarroPasajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carro', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Propietario')),
            ],
            options={
                'verbose_name': 'Carro de Pasajes',
                'verbose_name_plural': 'Carros de Pasajes',
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Santiago, Valparaíso, Concepción.', max_length=100, verbose_name='Nombre de Ciudad')),
                ('terminal', models.CharField(help_text='Ej: Terminal Sur, Terminal Rodoviario, Terminal Collao.', max_length=150, verbose_name='Nombre del Terminal')),
                ('region', models.CharField(help_text='Región administrativa en Chile.', max_length=100, verbose_name='Región')),
            ],
            options={
                'verbose_name': 'Ciudad / Terminal',
                'verbose_name_plural': 'Ciudades y Terminales',
                'ordering': ['nombre'],
                'unique_together': {('nombre', 'terminal')},
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Total Pagado (CLP)')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('CANCELADO', 'Cancelado'), ('COMPLETADO', 'Completado')], default='PENDIENTE', max_length=20, verbose_name='Estado de la Orden')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to=settings.AUTH_USER_MODEL, verbose_name='Pasajero Comprador')),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia_km', models.PositiveIntegerField(verbose_name='Distancia en KM')),
                ('duracion_estimada_minutos', models.PositiveIntegerField(verbose_name='Duración Estimada (Minutos)')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_destino', to='transporte.ciudad', verbose_name='Ciudad Destino')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_origen', to='transporte.ciudad', verbose_name='Ciudad Origen')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
                'ordering': ['origen__nombre', 'destino__nombre'],
                'unique_together': {('origen', 'destino')},
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_salida', models.DateTimeField(verbose_name='Fecha y Hora de Salida')),
                ('fecha_hora_llegada', models.DateTimeField(verbose_name='Fecha y Hora Estimada de Llegada')),
                ('precio_semicama', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Tarifa Semicama (CLP)')),
                ('precio_cama', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Tarifa Cama (CLP)')),
                ('estado', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_RUTA', 'En Ruta'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PROGRAMADO', max_length=20, verbose_name='Estado Operativo del Servicio')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='transporte.bus', verbose_name='Bus Asignado')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='transporte.ruta', verbose_name='Ruta del Servicio')),
            ],
            options={
                'verbose_name': 'Servicio / Itinerario',
                'verbose_name_plural': 'Servicios e Itinerarios',
                'ordering': ['fecha_hora_salida'],
            },
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Código Único de Boleto (UUID)')),
                ('nombre_pasajero', models.CharField(max_length=150, verbose_name='Nombre Completo del Ocupante')),
                ('rut_pasajero', models.CharField(max_length=20, verbose_name='RUT / Pasaporte del Ocupante')),
                ('precio_pagado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Pagado')),
                ('activo', models.BooleanField(default=True, help_text='Si se cancela la orden, se desactiva para reponer el asiento al inventario.', verbose_name='¿Boleto Válido y Ocupando Asiento?')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boletos', to='transporte.asiento', verbose_name='Asiento Asignado')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletos', to='transporte.ordencompra', verbose_name='Orden de Compra')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boletos', to='transporte.servicio', verbose_name='Servicio Itinerario')),
            ],
            options={
                'verbose_name': 'Boleto de Viaje',
                'verbose_name_plural': 'Boletos de Viaje',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='ItemCarro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pasajero', models.CharField(max_length=150, verbose_name='Nombre Completo del Ocupante')),
                ('rut_pasajero', models.CharField(max_length=20, verbose_name='RUT / Pasaporte del Ocupante')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Congelado al Agregar')),
                ('agregado_en', models.DateTimeField(auto_now_add=True)),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_en_carro', to='transporte.asiento', verbose_name='Asiento Seleccionado')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transporte.carropasajes', verbose_name='Carro Asociado')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_en_carro', to='transporte.servicio', verbose_name='Servicio Seleccionado')),
            ],
            options={
                'verbose_name': 'Ítem de Carro',
                'verbose_name_plural': 'Ítems de Carro',
                'ordering': ['agregado_en'],
                'unique_together': {('carro', 'servicio', 'asiento')},
            },
        ),
    ]
