# Generated by Django 6.1 on 2026-09-28 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Turbus, Pullman Bus, EME Bus.', max_length=120, unique=True, verbose_name='Nombre de Empresa / Tenant')),
                ('rut', models.CharField(help_text='Identificador tributario único (ej: 76.123.456-7).', max_length=20, unique=True, verbose_name='RUT Empresa')),
                ('slug', models.SlugField(help_text="Identificador único para URLs o filtros (ej: 'turbus', 'pullman').", max_length=60, unique=True, verbose_name='Identificador Tenant (Slug)')),
                ('color_hex', models.CharField(default='#1e3a8a', help_text="Color corporativo para el frontend (ej: '#0284c7').", max_length=10, verbose_name='Color de Marca (HEX)')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Empresa Operativa?')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa de Transporte (Tenant)',
                'verbose_name_plural': 'Empresas de Transporte (Tenants)',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='bus',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='transporte.empresatransporte', verbose_name='Empresa Propietaria (Tenant)'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='transporte.empresatransporte', verbose_name='Empresa Operadora (Tenant)'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Si el usuario es Administrador de Flota, determina el Tenant al que pertenece.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administradores', to='transporte.empresatransporte', verbose_name='Empresa Asignada (Tenant)'),
        ),
    ]
