# Generated by Django 6.1 on 2026-09-28 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0002_empresatransporte_bus_empresa_servicio_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='estado_embarque',
            field=models.CharField(choices=[('EMITIDO', 'Boleto Emitido / Pendiente Abordaje'), ('EMBARCADO', 'Pasajero a Bordo'), ('NO_SHOW', 'No se Presentó (No Show)')], default='EMITIDO', help_text='Control de abordaje físico del pasajero en la máquina.', max_length=20, verbose_name='Estado de Embarque'),
        ),
        migrations.AddField(
            model_name='bus',
            name='estado_operativo',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible en Terminal'), ('EN_RUTA', 'En Ruta / Asignado'), ('MANTENIMIENTO', 'En Mantenimiento Preventivo'), ('FUERA_SERVICIO', 'Fuera de Servicio')], default='DISPONIBLE', help_text='Define si la máquina está disponible en terminal, en ruta, en mantenimiento o fuera de servicio.', max_length=20, verbose_name='Estado Operativo de la Máquina'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='metodo_pago',
            field=models.CharField(choices=[('WEBPAY', 'Webpay Plus / Débito - Crédito'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('EFECTIVO', 'Efectivo en Boletería'), ('BANCO_ESTADO', 'CuentaRUT / BancoEstado')], default='WEBPAY', help_text='Pasarela o medio de pago seleccionado por el cliente.', max_length=20, verbose_name='Método de Pago'),
        ),
    ]
